// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMRwfR905GWdj-8kLA8Aah9BCQTQd6mmY',
    appId: '1:499762911206:web:3381215d4020814a492827',
    messagingSenderId: '499762911206',
    projectId: 'birdsviewapp-9d25a',
    authDomain: 'birdsviewapp-9d25a.firebaseapp.com',
    storageBucket: 'birdsviewapp-9d25a.appspot.com',
    measurementId: 'G-3KGD144HRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUgXBrpMNpP8az5g-3H7fLjfLvUCrw3-M',
    appId: '1:499762911206:android:20ae6b9fbae4ca0a492827',
    messagingSenderId: '499762911206',
    projectId: 'birdsviewapp-9d25a',
    storageBucket: 'birdsviewapp-9d25a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS11d9W47MR32DdnjumQYO42zOSjrdvPo',
    appId: '1:499762911206:ios:97cbb1bcbc8e7721492827',
    messagingSenderId: '499762911206',
    projectId: 'birdsviewapp-9d25a',
    storageBucket: 'birdsviewapp-9d25a.appspot.com',
    androidClientId: '499762911206-t8esgkiqknjq649fimcunq75092amupq.apps.googleusercontent.com',
    iosClientId: '499762911206-th3l8l6ahoi4vsrq9sq9icoal5gcmed9.apps.googleusercontent.com',
    iosBundleId: 'com.birds.view.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS11d9W47MR32DdnjumQYO42zOSjrdvPo',
    appId: '1:499762911206:ios:572ffd8aa7a9e58a492827',
    messagingSenderId: '499762911206',
    projectId: 'birdsviewapp-9d25a',
    storageBucket: 'birdsviewapp-9d25a.appspot.com',
    androidClientId: '499762911206-t8esgkiqknjq649fimcunq75092amupq.apps.googleusercontent.com',
    iosClientId: '499762911206-9vook2hp3ugj35hvpmnkid0vf06sv24n.apps.googleusercontent.com',
    iosBundleId: 'com.example.birdsView',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMRwfR905GWdj-8kLA8Aah9BCQTQd6mmY',
    appId: '1:499762911206:web:c5d41e393680b75e492827',
    messagingSenderId: '499762911206',
    projectId: 'birdsviewapp-9d25a',
    authDomain: 'birdsviewapp-9d25a.firebaseapp.com',
    storageBucket: 'birdsviewapp-9d25a.appspot.com',
    measurementId: 'G-CT8W1SW2KG',
  );
}
