String baseUrl = "https://owlapi.zemfar.com/api/";
String loginUrl = "login";
String fetchProfileUrl = "fetch-profile?id=";
String checkEmailUrl = "forget-password";
String resetPasswordUrl = "password-reset";
String registerUrl = "register";
String loginApi = baseUrl + loginUrl;
String fetchProfileApi = baseUrl + fetchProfileUrl;
String checkEmailApi = baseUrl + checkEmailUrl;
String resetPasswordApi = baseUrl + resetPasswordUrl;
String registerApi = baseUrl + registerUrl;
